# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: build
    projects: 'WAK_Session_01/WAK_Session_01.sln'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --verbosity normal'
    publishWebProjects: true
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'WAK_Session_01/Service.UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration) --verbosity normal --list-tests'
    testRunTitle: 'Unit Tests'

- task: DotNetCoreCLI@2
  displayName: pulish
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --verbosity detailed'
    publishWebProjects: true
    zipAfterPublish: true
